!include $(NTMAKEENV)\makefile.def

clean:
	-del buildfre.log
	-del i386\mayudrsc.sys
	-del i386\mayudrsc.pdb
	-del obj\_objects.mac
	-del objfre\i386\\mayudrsc.obj
	-del *~
	-rd i386
	-rd obj
	-rd objfre\i386
	-rd objfre
