#ifndef _IOCTL_H
#define _IOCTL_H

#define TOUCHPAD_SCANCODE 0xfe

// Ioctl value
#define IOCTL_MAYU_DETOUR_CANCEL					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MAYU_GET_VERSION					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MAYU_GET_LOG					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MAYU_FORCE_KEYBOARD_INPUT				 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x804, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#endif // !_IOCTL_H
