!include $(NTMAKEENV)\makefile.def

clean:
	-del buildfre.log
	-del i386\mayud.sys
	-del i386\mayud.pdb
	-del obj\_objects.mac
	-del objfre\i386\*.obj
	-del objfre\i386\*.mac
	-del objfre_wxp_x86\i386\*.obj
	-del objfre_wxp_x86\*.mac
	-del *~
	-rd obj
	-rd objfre\i386
	-rd objfre
	-rd objfre_wxp_x86\i386
	-rd objfre_wxp_x86
