#!/usr/bin/perl -w

if ( $#ARGV < 3 ) {
  printf("usage: geniexpress SFX.EXE TITLE SETUP.EXE [Files...]\n");
  exit(1);
}

$TargetName   = shift @ARGV;
$FriendlyName = shift @ARGV;
$AppLaunched  = shift @ARGV;

$template = <<"__EOM__";
[Version]
Class=IEXPRESS
SEDVersion=3

[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=$TargetName
FriendlyName=$FriendlyName
AppLaunched=$AppLaunched
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles

[SourceFiles]
SourceFiles0=.\\

[SourceFiles0]
__EOM__

foreach $i ( sort @ARGV ) {
  $template .= "$i=\n";
}
print $template;
